
dist: bionic
language: python
# Reduce the amount of downloaded data from 50MiB to 7MiB
git:
  depth: 1
matrix:
  include:
    - python: 3.9
      os: linux
      env:
        - RUN_COVERAGE=true
        - MAKE_SECP=false

    - python: 3.7
      os: linux
      env:
        - RUN_COVERAGE=false
        - MAKE_SECP=true
install:
  - if [ "$MAKE_SECP" == true ];
    then
        ./contrib/make_secp;
    fi
  - pip install -r contrib/requirements/requirements-ci.txt
cache:
  - pip
script:
  - if [ "$RUN_COVERAGE" == true ];
    then
        coverage run -m electroncash.tests;
        coverage run -m electrumabc_plugins.fusion.tests;
        coverage report --include="./electroncash*";
    else
        python -m electroncash.tests;
        python -m electrumabc_plugins.fusion.tests;
    fi
